# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subjects', models.CharField(max_length=200)),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('subjects', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShare.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='reviewers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookShare.user'),
        ),
    ]
