# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookShare', '0002_auto_20170408_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Uuser',
        ),
    ]
