# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookShare', '0003_auto_20170408_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uuser',
            options={'get_latest_by': 'creation_date'},
        ),
        migrations.AddField(
            model_name='uuser',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
